# Generated by Django 5.0.4 on 2024-04-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface_data',
            old_name='method',
            new_name='level',
        ),
    ]
