# Generated by Django 5.0.4 on 2024-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_method_interface_data_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_data',
            name='goal',
            field=models.TextField(),
        ),
    ]
