# Generated by Django 5.0.4 on 2024-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_interface_data_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_data',
            name='cintent_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='content_stay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='question_analysis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='question_application',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='question_evaluation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='question_remember',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='question_understanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='quiz_revsions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='self_assess_stay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='self_assess_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='video_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='video_visit',
            field=models.IntegerField(default=0),
        ),
    ]
