# Generated by Django 5.0.4 on 2024-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_interface_data_cintent_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_data',
            name='content_type',
            field=models.CharField(default='N/A', max_length=122),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='platform',
            field=models.CharField(default='N/A', max_length=122),
        ),
        migrations.AlterField(
            model_name='interface_data',
            name='goal',
            field=models.CharField(default='N/A', max_length=122),
        ),
        migrations.AlterField(
            model_name='interface_data',
            name='language',
            field=models.CharField(default='N/A', max_length=122),
        ),
        migrations.AlterField(
            model_name='interface_data',
            name='level',
            field=models.CharField(default='N/A', max_length=122),
        ),
    ]
