# Generated by Django 5.0.1 on 2024-05-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_interface_data_content_type_interface_data_platform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface_data',
            old_name='cintent_visit',
            new_name='content_stay_gfg',
        ),
        migrations.RenameField(
            model_name='interface_data',
            old_name='content_stay',
            new_name='content_stay_w3school',
        ),
        migrations.RenameField(
            model_name='interface_data',
            old_name='quiz_revsions',
            new_name='content_visit_gfg',
        ),
        migrations.RenameField(
            model_name='interface_data',
            old_name='level',
            new_name='level_of_understanding',
        ),
        migrations.AddField(
            model_name='interface_data',
            name='content_visit_w3school',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='total_interactions',
            field=models.IntegerField(default=0),
        ),
    ]
