# Generated by Django 5.0.1 on 2024-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_cintent_visit_interface_data_content_stay_gfg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_data',
            name='preference_gfg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='preference_w3school',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interface_data',
            name='preference_youtube',
            field=models.FloatField(default=0),
        ),
    ]
